### ISSUE TITLE
Configure using the `with` parameter

### ISSUE THREAD

**Issue by TimonVS** [TimonVS/pr-labeler-action#11]
Configuration should be done using the `with` parameter instead of having to create a separate YAML file. We can still keep support for the YAML file as not to cause breaking changes for people who use the `master` version of this Action, or we could create a ticket in the repo to give users a heads up.

**Comment by amacado** [comment]
Maybe you could make an example, i'm not sure if I understand what u mean

**Comment by TimonVS** [comment]
```yml
name: PR Labeler
on:
  pull_request:
    types: [opened]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@master
        with:
          feature: ['feature/*', 'feat/*']
          fix: fix/*
          chore: chore/*
          fixed-branch: fixed-branch-name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

In the above example each parameter provided to the `with` parameter will be exposed as an environment variable prefixed with `INPUT_` (see https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepswith). So we can filter `process.env` to only include environment variables that are prefixed with `INPUT_` and we have our config. The only downside is that an environment variable is always a string. So the array in the above example has to be evalled and another list syntax won't work. The huge benefit is that configuration can be done right within the workflow instead of having to create a separate YAML file.
