### ISSUE TITLE
Action doesn't work for forks (Resource not accessible by integration)

### ISSUE THREAD

**Issue by TimonVS** [TimonVS/pr-labeler-action#25]
The Action fails to run on PRs that are submitted from a fork. As an example see the failing check on [#24](https://github.com/TimonVS/pr-labeler-action/pull/24/checks). It's basically the same issue as https://github.com/actions/labeler/issues/12.

**Comment by JohnRDOrazio** [comment]
I was able to implement for PR's coming from forks by the `pull_request_target` action instead of the `pull_request` action:

```yml
name: PR Labeler
on:
  pull_request_target:
    types: [opened]
```
