### ISSUE TITLE
Label filters based on Head & Base 

### ISSUE THREAD

**Issue by deepakputhraya** [TimonVS/pr-labeler-action#27]
Are there any plans to add labels based on regex matching head/base branch?

Current config - 
```
feature: ['feature/*', 'feat/*']
fix: fix/*
chore: chore/*
fixed-branch: fixed-branch-name
```

Suggested config
```
feature:
  head: ["feature/*", "feat/*"]
hotfix:
  base: master
  ignore: ["develop"]
release:
  head: develop
  base: master
```

This could give more control over labelling.

**Comment by amacado** [comment]
Hello @deepakputhraya, I appreciate your idea. Could you be so kind and specify what you mean with the `ignore: ["develop"]` configuration? We should also discuss if the specified conditions would be combined in an "AND" or "OR" statement. I would prefer the "AND" matching like when given _base_ matches and when given _head_ matches the specified regex _then_ add the label.

**Comment by deepakputhraya** [comment]
> We should also discuss if the specified conditions would be combined in an "AND" or "OR" statement. I would prefer the "AND" matching like when given base matches and when given head matches the specified regex then add the label.
Apologies not being explicit. I just assumed the AND case with `head` & `base` fields. And the list being OR. 

> Could you be so kind and specify what you mean with the ignore: ["develop"] configuration?
I would like to make a small correction 
```
hotfix:
  base: master
  ignore_head: ["develop"] # changed from ignore to ignore_head
```
Ignore branches with specific names for this rule. This is probably possible to support with regex but the thought here was to make the rule more readable.

Do you think adding filter like PR size to this make sense? I understand that there are Github actions for this specific scenario, but providing PR size filter with base & head would make it more customizable. 
Example:

```
hotfix:
  base: master
  head: "hotfix/*"
  max_line_changes: 10 
```
Assuming that it is AND across properties and OR within a property.
