### ISSUE TITLE
Question: Additional Commit Categories

### ISSUE THREAD

**Issue by Mike-EEE** [TimonVS/pr-labeler-action#28]
Cool project!  I was looking into Release Drafter and found the link here.

Everything looks great... my only question is the types of categories supported by Conventional Commit:

- [x] feat 
- [x] fix  
- [ ] docs 
- [ ] style 
- [ ] refactor
- [ ] perf
- [ ] test
- [ ] build
- [ ] ci
- [x] chore
- [ ] revert

I've checked the ones that the `README` states are definitely supported... I was curious about the remaining ones.  Are we able to configure these as well?

Thanks for your efforts in building (and supporting 😁) this!

**Comment by TimonVS** [comment]
Hey, all of those are supported by adding a config file :)
The ones you mention are the ones covered by the default configuration, which are overwritten once you add a custom config.

`.github/pr-labeler.yml`

```yml
feature: ['feature/*', 'feat/*']
fix: fix/*
chore: chore/*
docs: docs/*
style: style/*
# etc.
```
