### ISSUE TITLE
Can't get it to work in new yml format

### ISSUE THREAD

**Issue by roni-frantchi** [TimonVS/pr-labeler-action#5]
```yml
# repo/.github/pr-labeler.yml

feature: ['feature-*', 'feat-*']
fix: fix-*
chore: chore-*
```

```yml
# repo/.github/workflows/pr-labeler.yml
name: Label PRs

on: [pull_request]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler@master
        if: github.event.action == 'opened'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Opened a PR named `chore-xxx`.

Output:
```
Run TimonVS/pr-labeler@master 1s
/usr/bin/docker run --name fe0f7da0b1cc59af4aa18a61b21c5bd6dc2b_84031a --label 29fe0f --workdir /github/workspace --rm -e GITHUB_TOKEN -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/env0/env0":"/github/workspace" 29fe0f:7da0b1cc59af4aa18a61b21c5bd6dc2b
Run TimonVS/pr-labeler@master
  env:
    GITHUB_TOKEN: ***
/usr/bin/docker run --name fe0f7da0b1cc59af4aa18a61b21c5bd6dc2b_84031a --label 29fe0f --workdir /github/workspace --rm -e GITHUB_TOKEN -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/env0/env0":"/github/workspace" 29fe0f:7da0b1cc59af4aa18a61b21c5bd6dc2b
```
