### ISSUE TITLE
Add config option to only apply first match

### ISSUE THREAD

**Issue by KevinBatdorf** [TimonVS/pr-labeler-action#52]
I'd like to have a fallback label applied without any matches.

```
feature: ['feature/*', 'feat/*']
fix: fix/*
chore: chore/*
unknown: *
```

So if nothing matches, it will add the label "unknown"

I was thinking you could add a config option where it would return on the first match instead of looping through each (then it would use the `*` as the fallback if nothing else matched). Does that seem feasible?

**Comment by w5l** [comment]
This might be a lot easier to do using the action config instead of in the tags `yml`.

For example:

```yml
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          default-label: 'unknown' # Any PR not matching one of the rules gets this label
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
