### ISSUE TITLE
usage of branches or branches-ignore breaks workflow

### ISSUE THREAD

**Issue by jeffvg** [TimonVS/pr-labeler-action#79]
Hi all,
I've been using PR-labeler for a over a year and works great. Since we started using the dependabot dependency update workflow and the security dependabot. The dependabot PR fails to run the PR labeler due to permissions. How can the current pr-labeler-action@v4 be configured to ignore dependabot PR's all together and not fail the job?

I've tried both these configs

```
name: PR Labeler
on:
  pull_request:
    types: [opened]
    branches:
      - '!dependabot/*'  //using not dependabot

permissions:
  contents: read

jobs:
  pr-labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/pr-labeler.yml
```
```
name: PR Labeler
on:
  pull_request:
    types: [opened]
    branches-ignore:  //using branches-ignore
      - 'dependabot/*'

permissions:
  contents: read

jobs:
  pr-labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/pr-labeler.yml
```
- error
![image](https://user-images.githubusercontent.com/37150565/223163374-945600d1-48b8-4260-9487-165c66583dc2.png)

thank you
